export { HeroSection } from "./HeroSection";
export { CategoriesSection } from "./CategoriesSection";
export { FunctionariesSection } from "./FunctionariesSection";
export { ResultsSection } from "./ResultsSection";
export { GallerySection } from "./GallerySection";
export { VirtualTourSection } from "./VirtualTourSection";
export { AboutSection } from "./AboutSection";
export { FeePaymentSection } from "./FeePaymentSection";
export { CTASection } from "./CTASection";
